### PR TITLE
v27.1.7 Update

### LINKED ISSUE #5: [bug]: Large File Uploads (>2.5GB) Fail, Error when assembling chunks, status code 504✖
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

5.18

### Browser

Firefox

### Browser Version

102

### Current Behavior

Uploading a file larger than ~2.5GB will fail, or throw an error and leave a corrupted/incomplete file on the server

Error:
Error when assembling chunks, status code 504✖

### Expected Behavior

File uploads up to several GB should function

### Steps to Reproduce

1. Attempt to upload a large file into Files
2. See error

### Anything else?

This is not unknown to NC, with some mitigation possible, but no permanent fix known it seems https://github.com/nextcloud/server/issues/17992

### PR DESCRIPTION
**Pull request by kn0wmad**
Closes #5, #59, #60

### CODE REVIEW

File: scripts/services/migrations.ts [hunk 1]
```diff
@@ -28,7 +28,7 @@ export const migration: T.ExpectedExports.migration = async (
 
   if (
     emver.values[0] == minMajor &&
-    minMajor >= 26 &&
+    minMajor >= 27 &&
```
Comment (dr-bonez) [inline scripts/services/migrations.ts:31]:
```suggestion
    minMajor >= 26 &&
```

File: scripts/services/migrations.ts [hunk 2]
```diff
@@ -88,6 +88,20 @@ export const migration: T.ExpectedExports.migration = async (
           );
         },
       },
+      "26.0.8.2": {
+        up: compat.migrations.updateConfig(
+          (_) => ({
+            "webdav": "1024",
```
Comment (dr-bonez) [inline scripts/services/migrations.ts:94]: this doesn't look right

File: nginx.conf [hunk 3]
```diff
@@ -143,7 +143,7 @@ server {
     # to the URI, resulting in a HTTP 500 error response.
     location ~ \.php(?:$|/) {
         # Required for legacy support
-        rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;
+        rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|ocs-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;
```
Comment (dr-bonez) [inline nginx.conf:146]: ocm no longer a thing?

File: nextcloud-run.sh [hunk 4]
```diff
@@ -116,6 +121,17 @@ echo "Starting Nextcloud frontend..."
...
+# Configure .user.ini
+echo "Configuring Nextcloud frontend..."
+sed -i "/php_value upload_max_filesize .*/d" $PHP_USER_FILE
+sed -i "/php_value post_max_size .*/d" $PHP_USER_FILE
+sed -i "/php_value max_input_time .*/d" $PHP_USER_FILE
+sed -i "/php_value max_execution_time .*/d" $PHP_USER_FILE
+echo 'php_value upload_max_filesize 16G' >> $PHP_USER_FILE
+echo 'php_value post_max_size 16G' >> $PHP_USER_FILE
+echo 'php_value max_input_time 3600' >> $PHP_USER_FILE
+echo 'php_value max_execution_time 3600' >> $PHP_USER_FILE
```
Comment (dr-bonez) [inline nextcloud-run.sh:133]: why switch to doing this every time?

**Review by dr-bonez — CHANGES_REQUESTED** [review]

File: nextcloud-run.sh (hunk 4 above)
Comment (kn0wmad) [reply nextcloud-run.sh:133]: I think this wasn't being done at all iirc.  I ran it in here because running at init won't work since NC must be running

File: nginx.conf (hunk 3 above)
Comment (kn0wmad) [reply nginx.conf:146]: This was an attempt to fix collabora - it did not work, and that feature is being punted.  I can revert this?

File: scripts/services/migrations.ts (hunk 2 above)
Comment (kn0wmad) [reply scripts/services/migrations.ts:94]: It does migrate properly, but throws an error (`No Match: webdav: Field Is Not Nullable`) - I'm not sure why, this is identical to the previous migration for default locales.  Does it need to be passed `config` instead of `_`?

Comment (dr-bonez) [reply scripts/services/migrations.ts:94]: This overwrites the entire config, rather than setting just the value you want. I don't think that's what you want. Try something like `config => { config.webdav = 1024; return config }`

File: nginx.conf (hunk 3 above)
Comment (dr-bonez) [reply nginx.conf:146]: If you don't understand it, it's probably better to leave it as it is

**Review by dr-bonez — APPROVED** [review]
